# Generated by Django 5.1 on 2024-09-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WordOfTheDay",
            new_name="DailyWord",
        ),
        migrations.AddField(
            model_name="word",
            name="english_definition",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
