# Generated by Django 5.1 on 2024-09-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_wordoftheday_dailyword_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyWord",
        ),
    ]
